# Generated by Django 3.1.4 on 2021-02-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210202_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 22, 0, 52, 733291)),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'attendance_date')},
        ),
    ]
