# Generated by Django 3.1.4 on 2021-02-04 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210203_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 4, 23, 32, 56, 103435)),
        ),
    ]
