# Generated by Django 3.1.4 on 2021-02-05 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210205_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 11, 40, 29, 905116)),
        ),
    ]
