# Generated by Django 3.1.4 on 2022-03-25 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210205_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 13, 7, 39, 254050)),
        ),
    ]
