# Generated by Django 3.1.4 on 2022-03-25 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220325_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 14, 51, 57, 57183)),
        ),
    ]
